export const MARK_ATTENDANCE_REQUEST = 'MARK_ATTENDANCE_REQUEST'
export const MARK_ATTENDANCE_SUCCESS = 'MARK_ATTENDANCE_SUCCESS'
export const MARK_ATTENDANCE_FAILED = 'MARK_ATTENDANCE_FAILED'

export const VIEW_ATTENDANCE_REQUEST = 'VIEW_ATTENDANCE_REQUEST'
export const VIEW_ATTENDANCE_SUCCESS = 'VIEW_ATTENDANCE_SUCCESS'
export const VIEW_ATTENDANCE_FAILED = 'VIEW_ATTENDANCE_FAILED'

