export const EMPLOYEE_ADD_REQUEST = 'EMPLOYEE_ADD_REQUEST'
export const EMPLOYEE_ADD_SUCCESS = 'EMPLOYEE_ADD_SUCCESS'
export const EMPLOYEE_ADD_FAILED = 'EMPLOYEE_ADD_FAILED'


export const EMPLOYEE_VIEW_REQUEST = 'EMPLOYEE_VIEW_REQUEST'
export const EMPLOYEE_VIEW_SUCCESS = 'EMPLOYEE_VIEW_SUCCESS'
export const EMPLOYEE_VIEW_FAILED = 'EMPLOYEE_VIEW_FAILED'
