export const APPLY_LEAVE_REQUEST = 'APPLY_LEAVE_REQUEST'
export const APPLY_LEAVE_SUCCESS = 'APPLY_LEAVE_SUCCESS'
export const APPLY_LEAVE_FAILED = 'APPLY_LEAVE_FAILED'


export const VIEW_LEAVE_REQUEST = 'VIEW_LEAVE_REQUEST'
export const VIEW_LEAVE_SUCCESS = 'VIEW_LEAVE_SUCCESS'
export const VIEW_LEAVE_FAILED = 'VIEW_LEAVE_FAILED'