export const GET_ALL_PAYSLIP_REQUEST = 'GET_ALL_PAYSLIP_REQUEST'
export const GET_ALL_PAYSLIP_SUCCESS = 'GET_ALL_PAYSLIP_SUCCESS'
export const GET_ALL_PAYSLIP_FAILED = 'GET_ALL_PAYSLIP_FAILED'

export const UPLOAD_ALL_PAYSLIP_REQUEST = 'UPLOAD_ALL_PAYSLIP_REQUEST'
export const UPLOAD_ALL_PAYSLIP_SUCCESS = 'UPLOAD_ALL_PAYSLIP_SUCCESS'
export const UPLOAD_ALL_PAYSLIP_FAILED = 'UPLOAD_ALL_PAYSLIP_FAILED'

export const GET_SINGLE_PAYSLIP_REQUEST= 'GET_SINGLE_PAYSLIP_REQUEST'
export const GET_SINGLE_PAYSLIP_SUCCESS= 'GET_SINGLE_PAYSLIP_SUCCESS'
export const GET_SINGLE_PAYSLIP_FAILED= 'GET_SINGLE_PAYSLIP_FAILED'

export const UPDATE_SINGLE_PAYSLIP_REQUEST = 'UPDATE_SINGLE_PAYSLIP_REQUEST'
export const UPDATE_SINGLE_PAYSLIP_SUCCESS = 'UPDATE_SINGLE_PAYSLIP_SUCCESS'
export const UPDATE_SINGLE_PAYSLIP_FAILED = 'UPDATE_SINGLE_PAYSLIP_FAILED'

